name: todos_api
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: 3.7.0

dependencies:
  freezed_annotation: 2.4.4
  json_annotation: 4.9.0

dev_dependencies:
  build_runner: 2.4.15
  freezed: 2.5.8
  json_serializable: 6.9.4
  test: 1.25.15